project:
  type: book
  preview:
    port: 4200
    browser: false

book:
  title: "Disinfo Dictionary"
  subtitle: "A dictionary of Myths and Truths"
  #description: "This dictionary consolidates and debunks chronic disinformation narratives detected by several fact-checking organisations."
  author: "Fellas & Partners"
  date: last-modified
  #site-url: http://127.0.0.1:4321
  #site-url: https://disinfodict.pages.dev
  #site-url: https://disinfodict.org
  #site-url: https://disdict.pages.dev
  site-url: https://disdict.org
  favicon: /all_common_img/DisinfoDict_logo_1x1_trans_small.png
  image: /all_common_img/DisinfoDict_logo_1x1_trans.png
  image-alt: "Logo of Disinfo Dictionary"
  downloads: [pdf,epub]
  #https://www.opengraph.xyz/
  open-graph: 
    image: /all_common_img/DisinfoDict_opengraph_1200x627.png
  twitter-card:
    card-style: "summary"
    image: /all_common_img/DisinfoDict_logo_144x144.png
  sidebar: 
    style: "floating"
    collapse-level: 1
    logo: all_common_img/DisinfoDict_logo_1x1_trans.png
    title: "search. read. share."
  #body-header: | 
  #  ::: {.callout-important title="BREAKING" appearance="default" collapse="false"}
  #  These are breaking NEWS
  #  :::
  page-footer:
    background: "grey"
    center:
      - text: "Impressum"
        href: impressum.qmd

  chapters:
  - index.qmd
  - part: "Status" 
    part-de: "Status" 
    chapters:
    - status/status.qmd
  - part: "Intro" 
    part-de: "Intro" 
    chapters:
    - intro/preface.qmd
    - intro/principles.qmd
    - intro/termstech.qmd
    - intro/ualessons.qmd
    - intro/trueukraine.qmd
    - intro/vatniks.qmd
    - intro/narratives.qmd
  - part: "Brothers"
    part-de: "Brüder"
    chapters:
    - brothers/russia.qmd
    - brothers/ukraine.qmd
  - part: "Church"
    part-de: "Kirche"
    chapters:
    - church/russia.qmd
    - church/ukraine.qmd
  - part: "Colonies"
    part-de: "Kolonien"
    chapters:
    - colonies/russia.qmd
    - colonies/ukraine.qmd
  - part: "Corruption"
    part-de: "Korruption"
    chapters:
    - corruption/russia.qmd
    - corruption/ukraine.qmd
  - part: "Crimea"
    part-de: "Krim"
    chapters:
    - crimea/history.qmd
    - crimea/annexation.qmd
    - crimea/purges.qmd
  - part: "Culture"
    part-de: "Kultur"
    chapters:
    - culture/russia.qmd
    - culture/cannibalism.qmd
    - culture/ukraine.qmd
    - culture/architecture.qmd
    - culture/carpets.qmd
    - culture/clothes.qmd
    - culture/farming.qmd
    - culture/bees.qmd
    - culture/food.qmd
    - culture/faith.qmd
    - culture/arts.qmd
    - culture/music.qmd
    - culture/prose.qmd
    - culture/poetry.qmd
  - part: "Democracy"
    part-de: "Demokratie"
    chapters:
    - democracy/russia.qmd
    - democracy/ukraine.qmd
  - part: "Denial"
    part-de: "Leugnung"
    chapters:
    - denial/intro.qmd
    - denial/azerbaijan.qmd
    - denial/bucha.qmd
    - denial/chasivyar.qmd
    - denial/chernihiv.qmd
    - denial/crimea.qmd
    - denial/dnipro.qmd
    - denial/hroza.qmd
    - denial/invasion.qmd
    - denial/khakovka.qmd
    - denial/kramatorsk.qmd
    - denial/kremenchuk.qmd
    - denial/mariupol.qmd
    - denial/mh17.qmd
    - denial/okhmatdyt.qmd
    - denial/zaporizhzhia.qmd
    - denial/zoomurder.qmd
  - part: "Donbas"
    part-de: "Donbas"
    chapters:
    - donbas/genocide.qmd
    - donbas/separatists.qmd
  - part: "Economy"
    part-de: "Wirtschaft"
    chapters:
    - economy/europe.qmd
    - economy/ukraine.qmd
    - economy/russia.qmd
  - part: "Genocide"
    part-de: "Genozid"
    chapters:
    - genocide/definition.qmd
    - genocide/history.qmd
    - genocide/announced.qmd
    - genocide/ongoing.qmd
  - part: "Germany"
    part-de: "Deutschland"
    chapters:
    - germany/russia.qmd
    - germany/ukraine.qmd
  - part: "Language"
    part-de: "Sprache"
    chapters:
    - language/russia.qmd
    - language/russophonia.qmd
    - language/ukraine.qmd
  - part: "Maidan"
    chapters:
    - maidan/kyiv.qmd
    - maidan/odesa.qmd
  - part: "Minorities"
    part-de: "Minderheiten"
    chapters:
    - minorities/russia.qmd
    - minorities/ukraine.qmd
  - part: "NATO"
    chapters:
    - nato/expansion.qmd
    - nato/promise.qmd
    - nato/threat.qmd
  - part: "Nazis"
    chapters:
    - nazis/germany.qmd
    - nazis/ukraine.qmd
    - nazis/racism.qmd
    - nazis/russkimir.qmd
    - nazis/russia.qmd
    - nazis/truthsocial.qmd
  - part: "Negotiations"
    part-de: "Verhandlungen"
    chapters:
    - negotiations/endwar.qmd
    - negotiations/russia.qmd
    - negotiations/ukraine.qmd
  - part: "Nukes"
    part-de: "Nuklearwaffen"
    chapters:
    - nukes/ukraine.qmd
    - nukes/russia.qmd
    - nukes/propaganda.qmd
  - part: "Peace"
    part-de: "Frieden"
    chapters:
    - peace/cooperation.qmd
    - peace/ceasefire.qmd
    - peace/russia.qmd
    - peace/ukraine.qmd
    - peace/weapons.qmd
  - part: "Persons"
    part-de: "Personen"
    chapters:
    - persons/brandt.qmd
    - persons/gorbachev.qmd
    - persons/navalny.qmd
    - persons/putin.qmd
    - persons/stalin.qmd
    - persons/zelenskyy.qmd
  - part: "Russia"
    part-de: "Russland"
    chapters:
    - russia/history.qmd
    - russia/empire.qmd
    - russia/moscow.qmd
    - russia/life.qmd
    - russia/soul.qmd
    - russia/values.qmd
    - russia/opposition.qmd
  - part: "Russia's War"
    part-de: "Russland's Krieg"
    chapters:
    - ruwar/escalation.qmd
    - ruwar/goals.qmd
    - ruwar/hybrid.qmd
    - ruwar/proxy.qmd
    - ruwar/resilience.qmd
    - ruwar/sanctions.qmd
  - part: "Ukraine"
    chapters:
    - ukraine/heroes.qmd
    - ukraine/history.qmd
    - ukraine/kyiv.qmd
    - ukraine/nation.qmd
  - part: "US"
    part-de: "USA"
    chapters:
    - us/disinfodisorder.qmd
    - us/ovaloffice.qmd
  - part: "War crimes"
    part-de: "Kriegsverbrechen"
    chapters:
    - warcrimes/intro.qmd
    - warcrimes/children.qmd
    - warcrimes/civilians.qmd
    - warcrimes/clusterbombs.qmd
    - warcrimes/conscription.qmd
    - warcrimes/culture.qmd
    - warcrimes/food.qmd
    - warcrimes/humansafari.qmd
    - warcrimes/humanitarian.qmd
    - warcrimes/infrastructure.qmd
    - warcrimes/journalists.qmd
    - warcrimes/nature.qmd
    - warcrimes/nuclear.qmd
    - warcrimes/prisoners.qmd
    - warcrimes/sexual.qmd
    - warcrimes/torture.qmd
    - warcrimes/urbicide.qmd
  - part: "World War II"
    part-de: "II. Weltkrieg"
    chapters:
    - wwii/responsibility.qmd
    - wwii/liberation.qmd
  appendices:  
    - appendix/about.qmd
    - appendix/recommendations.qmd
    - appendix/references.qmd

callout-appearance: simple
bibliography: 
  - UkraineVerstehen.en.bib
  - UkraineVerstehen.de.bib
  - UkraineImFokus.bib
  - intro/preface.bib
  - intro/termstech.bib
  - intro/trueukraine.bib
  - intro/ualessons.bib
  - culture/russia.bib
  - corruption/ukraine.bib
  - genocide/definition.bib
  - nazis/russia.bib
  - russia/empire.bib
  - appendix/recommendations.bib

format:
  html:
    canonical-url: true
    theme: cosmo
    css: styles.css
    number-sections: true
    toc: true
    toc-depth: 3
    toc-expand: 1
    email-obfuscation: javascript
    link-external-icon: false
    link-external-newwindow: false
    license: CC BY-NC-ND
    include-in-header: 
      - file: in_header.html
  pdf:
    latex-auto-mk: true
    latex-tinytex: false
    pdf-engine: xelatex
    documentclass: scrbook
    toc: true
    number-sections: true
    colorlinks: true
    mainfont: "Segoe UI"
    include-in-header:
      text: |
        \usepackage{alphalph}
        \renewcommand*{\thepart}{%
          \AlphAlph{\value{part}}%
        }
        \usepackage{makeidx}
        \makeindex
        \newcommand{\LatexTableFontSize}{\fontsize{6}{9}\selectfont}
        \newcommand{\LatexReturnFontSize}{\fontsize{12}{14}\selectfont}
#        \renewcommand\thepart{\Alph{part}}
#better in references.qmd
#    include-after-body:
#      text: |
#        \printindex
  epub:
    accessibilitySummary: "This publication conforms to WCAG 2.0 Level AA."
    toc: true
    toc-depth: 3
    number-sections: true

babelquarto:
  languagecodes:
  - name: de
    text: "🇩🇪 Deutsch"
  - name: en
    text: "🇺🇸 English"
  mainlanguage: 'en'
  languages: ['de']
title-de: Desinfo-Lexikon
subtitle-de: Ein Lexikon der Mythen und Wahrheiten
#description-de: Dieses Lexikon konsolidiert und entkräftet chronische Desinformations-Narrative, die von verschiedenen Fact-Checking-Organisationen festgestellt wurden.
author-de: NAFO & Partner
lang: en

