# Welcome {.unnumbered}

> A fine line separates lies from the truth in the past, but in the future there is no longer any line.  
> — Lesja Ukrainka, Cassandra (1907)

The **Disinfo Dictionary** is a compact, clearly structured, searchable and linkable online resource that refutes recurring Russian narratives about Russia's war against Ukraine with selected facts, thus complementing the very extensive [EUvsDisinfo database](https://euvsdisinfo.eu/disinformation-cases/) of the EU diplomatic service and Wikipedia: DisinfoDict is a **time-saving tool for journalists, for fact-checkers, for activists against disinformation, for users of social networks and for all citizens looking for reliable information about Russia and Ukraine**.  DisinfoDict is both a lexicon for searching and looking up, or can be read from start to finish, online, on a smartphone, or offline as a pdf or epub; with a screen reader, the epub serves as an audio book.  DisinfoDict is bilingual (German/English), free, open source and extensible.  DisinfoDict is not yet complete, but it is already useful.

We hope that DisinfoDict will help to reduce the widespread narratives of 
Russian propaganda about the war against Ukraine and thus contribute 
to a more resilient society and security in Europe.		

**read. share. join.**

::: {.content-visible when-format="latex"}
The Disinfo Dictionary © 2024 by Fellas \& Partners is licensed under CC BY-NC-ND 4.0. To view a copy of this license, visit [creativecommons.org](https://creativecommons.org/licenses/by-nc-nd/4.0/)
:::

::: {.content-visible when-format="html"}
For barrier-free reading and listening we recommend the e-book 'epub' downloads in [English]({{<meta book.site-url>}}/Disinfor-Dictionary.epub) and [German]({{<meta book.site-url>}}/de/Desinfo-Lexikon.epub) language. 'pdf' downloads are also available [English]({{<meta book.site-url>}}/Disinfor-Dictionary.pdf) and [German]({{<meta book.site-url>}}/de/Desinfo-Lexikon.pdf). 

This website is multi-lingual: for switching language click on the globe-icon 🌐 top-left. This page is multi-format: you can read online, or download pdf or epub by clicking on the download-icon ⤓ top left. Part and chapter navigation is on the left, section navigation is on the right. To make section navigation visible on the smartphone, simply use the smartphone in landscape mode. To start reading, click on 'Preface' right at the bottom navigation. 

The Desinformation-Dictionary © 2024 by Fellas \& Partners is licensed under CC BY-NC-ND 4.0. To view a copy of this license, visit [creativecommons.org](https://creativecommons.org/licenses/by-nc-nd/4.0/)
:::

