# Willkommen {.unnumbered}

> Eine feine Linie trennt in der Vergangenheit die Lüge von der Wahrheit, aber in der Zukunft gibt es keine Linie mehr.  
> — Lesja Ukrainka, Cassandra (1907)

**Desinfo-Lexikon** ist eine kompakte, übersichtlich strukturierte, durchsuchbare und verlinkbare Online-Ressource, die wiederkehrende russische Narrative über Russlands Krieg gegen die Ukraine mit ausgewählten Fakten widerlegt, und so die sehr umfangreiche [EUvsDisinfo-Datenbank](https://euvsdisinfo.eu/disinformation-cases/) des diplomatischen Dienstes der EU und Wikipedia ergänzt: DisinfoDict ist ein **zeitersparendes Tool für Journalisten, für Fakten-Checker, für Aktivisten gegen Desinformation, für Nutzer sozialer Netzwerke und für alle Bürger, die zuverlässige Informationen über Russland und die Ukraine suchen**.  DisinfoDict ist sowohl ein Lexikon zum Suchen und Nachschlagen, oder kann von Anfang bis Ende gelesen werden, online, auf dem Smartphone, oder offline als pdf oder epub; mit einem Screenreader dient das epub als Hörbuch.  DisinfoDict ist zweisprachig (deutsch/englisch), kostenlos, quelloffen und erweiterbar.  DisinfoDict ist noch nicht komplett, aber schon nützlich.

Wir hoffen, dass DisinfoDict hilft, die weitverbreiteten Narrative russischer 
Propaganda über den Krieg gegen die Ukraine zu reduzieren und damit zu einer 
resilienteren Gesellschaft und zur Sicherheit in Europa beiträgt.

**read. share. join.**

::: {.content-visible when-format="latex"}
Das Desinfo-Lexikon © 2024 von Fellas & Partnern ist lizensiert unter CC BY-NC-ND 4.0. Für die vollständige Lizenz siehe [creativecommons.org](https://creativecommons.org/licenses/by-nc-nd/4.0/)
:::

::: {.content-visible when-format="html"}
Zum barrierefreien Lesen und Hören empfehlen wir die e-book 'epub' downloads in den Sprachen [Deutsch]({{<meta book.site-url>}}/de/Desinfo-Lexikon.epub) und [Englisch]({{<meta book.site-url>}}/Disinfo-Dictionary.epub). 'pdf' downloads sind ebenfalls verfügbar in [Deutsch]({{<meta book.site-url>}}/de/Desinfo-Lexikon.pdf) und [Englisch]({{<meta book.site-url>}}/Disinfo-Dictionary.pdf).

Diese Webseite ist mehrsprachig: Um die Sprache zu wechseln, klicken Sie auf das Globus-Icon 🌐 oben links. Diese Seite hat mehrere Formate: Sie können sie online lesen oder als pdf, epub oder docx herunterladen, indem Sie auf das Download-Icon ⤓ oben links klicken. Die Teil- und Kapitelnavigation befindet sich auf der linken Seite, die Abschnittsnavigation auf der rechten Seite. Um die Abschnittsnavigation auf dem Smartphone sichtbar zu machen, verwenden Sie das Smartphone einfach im Querformat. Um mit dem Lesen zu beginnen, klicken Sie auf „Vorwort“ rechts in der unteren Navigation.

Das Desinfo-Lexikon © 2024 von Fellas & Partnern ist lizensiert unter CC BY-NC-ND 4.0. Für die vollständige Lizenz siehe [creativecommons.org](https://creativecommons.org/licenses/by-nc-nd/4.0/)
:::
